# Generated by Django 6.1.1 on 2026-09-26 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('current_coffee_count', models.PositiveIntegerField(default=0)),
                ('prepaid_cards_remaining', models.PositiveIntegerField(default=0)),
                ('current_card_punch_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
